### ISSUE TITLE
it can not work for me. My environment is Ubuntu1404 and gazebo 7

### ISSUE THREAD

**Issue by HaoQChen** [aws-robotics/aws-robomaker-small-house-world#1]
![image](https://user-images.githubusercontent.com/13584792/54888740-c830f700-4eda-11e9-9fc0-3519c7b10bcc.png)
when i load the world, it looks like this, only black

**Comment by HaoQChen** [comment]
all right~~~I export 'pwd' to my path, not the real path

**Comment by punnpkin** [comment]
兄弟，你是怎么用的啊，我老是报这个错误：
```
gzclient: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.
```

**Comment by HaoQChen** [comment]
> 你是怎么用的啊，我老是报这个错误：

好久了，都基本忘了

**Comment by punnpkin** [comment]
> > 你是怎么用的啊，我老是报这个错误：
> 
> 好久了，都基本忘了

那问一下这个模型好用吗？或者还有没有什么好一点gazebo室内模型（哭

**Comment by xabxx** [comment]
> > > 你是怎么用的啊，我老是报这个错误：
> > 
> > 
> > 好久了，都基本忘了
> 
> 那问一下这个模型好用吗？或者还有没有什么好一点gazebo室内模型（哭

hello～如果你需要我们帮你看一下你的错误信息的话，可以麻烦新开一个issue或者重开这个issue吗？谢谢～

**Comment by xabxx** [comment]
#9 @punnpkin 才看到，不好意思哈。We will take a look.

**Comment by punnpkin** [comment]
> #9 @punnpkin 才看到，不好意思哈。We will take a look.

Thanks♪(･ω･)ﾉ感谢
