### ISSUE TITLE
Gazebo 10.2 on Ubuntu 16.02

### ISSUE THREAD

**Issue by gowin1** [aws-robotics/aws-robomaker-small-house-world#21]
When I run the following commands, I only see a blank Gazebo screen with some polygons (please see attached screenshot)

export GAZEBO_MODEL_PATH=`pwd`/models
gazebo worlds/small_house.world

![gazebo_blank](https://user-images.githubusercontent.com/64745530/80920653-075c8900-8d26-11ea-8a1e-2faa86b80f83.jpg)

**Comment by samuelgundry** [comment]
Appears to be broken on Gazebo 9 and Gazebo 11 too. I just reverted to `bbf887fa51` and the the world loads properly.

**Comment by piraka9011** [comment]
Reproduced on Ubuntu 18.04, Gazebo 11.0.
Opened #22 until a solution is found.

**Comment by mm318** [comment]
Hi @gowin1, can you see if this issue resolved, now that https://github.com/aws-robotics/aws-robomaker-small-house-world/pull/22 is merged?

**Comment by wangvnn** [comment]
I verified that [](https://github.com/aws-robotics/aws-robomaker-small-house-world/pull/22) work on Ubuntu 16.02 and Gazebo 10.2

**Comment by wangvnn** [comment]
I verified that [#22](https://github.com/aws-robotics/aws-robomaker-small-house-world/pull/22) work on Ubuntu 16.02 and Gazebo 10.2
