### ISSUE TITLE
GZWeb Support

### ISSUE THREAD

**Issue by piraka9011** [aws-robotics/aws-robomaker-small-house-world#23]
The ROS1 branch of this repo currently supports standalone Gazebo and ROS packages.

GZWeb however requires linting/pretty printing of the `dae` files for the models and a different URI path (model name only instead of `models/<model_name>`).

**Comment by kapilPython** [comment]
I tried running this on gzweb, and was able to generate collision for "aws_robomaker_residential_AirconditionerA_01" but the visual effect is still not working by changing models/aws_robomaker_residential_AirconditionerA_01/model.sdf

1)            uri>file://models/aws_robomaker_residential_AirconditionerA_01/meshes/aws_AirconditionerA_01_collision.DAE</uri> to             uri>model://aws_robomaker_residential_AirconditionerA_01/meshes/aws_AirconditionerA_01_collision.DAE</uri>
2)             <uri>file://models/aws_robomaker_residential_AirconditionerA_01/meshes/aws_AirconditionerA_01_visual.DAE</uri> to             <uri>model://aws_robomaker_residential_AirconditionerA_01/meshes/aws_AirconditionerA_01_visual.DAE</uri>

and changing models/aws_robomaker_residential_AirconditionerA_01/meshes/aws_AirconditionerA_01_visual.DAE

    <image id="MapFBXASC032FBXASC0352-image" name="MapFBXASC032FBXASC0352"><init_from>../materials/textures/aws_AirconditionerA_01.png</init_from></image> to     <image id="MapFBXASC032FBXASC0352-image" name="MapFBXASC032FBXASC0352"><init_from>model://aws_robomaker_residential_AirconditionerA_01/materials/textures/aws_AirconditionerA_01.png</init_from></image>

**Comment by kapilPython** [comment]
https://github.com/aws-robotics/aws-robomaker-small-warehouse-world/pull/7#issue-501202301

The Above pull request by me for aws-robotics-small-warehouse-world could be used here too.

**Comment by ahtsan** [comment]
@kapilPython Thank you for your contribution. We'll look into it and have it reviewed.

**Comment by kapilPython** [comment]
I hope this pull request could resolve the issue - 

https://github.com/aws-robotics/aws-robomaker-small-house-world/pull/32#issue-505525887

**Comment by ahtsan** [comment]
Pull request is merged
