### ISSUE TITLE
Ensure zero's of world is a location where robot can be spawned.

### ISSUE THREAD

**Issue by konduri** [aws-robotics/aws-robomaker-small-house-world#31]
Currently 0,0 is within walls of the world.

It would be great to follow convention of worldforge and have 0,0 spawable.

Use case: This world is a great default for sample applications that are build using worldforge. However, adding this as default would mean we have to modify starting positions with logic in launch file, which is not great user experience.

**Comment by ojasjoshi** [comment]
That's a good point @konduri. We will discuss and track this to make the necessary changes.

**Comment by ojasjoshi** [comment]
Hi @konduri, I have update the world so that 0,0 is now spawnable. Closing this feature request, please re-open if you find any issues.
