### ISSUE TITLE
A robot is not moving in the gazebo

### ISSUE THREAD

**Issue by han-kyung-min** [aws-robotics/aws-robomaker-small-house-world#39]
Hello,

Thanks for the nice gazebo simulator.

I was trying to launch this world with a Fetch robot in order to do an autonomous navigation task.

I could successfully launch both world and a Fetch robot. But, I cannot move the robot in this world. The robot is supposed to move if I publish /cmd_vel or /base_controller/command, but it does not.

Could you please give a piece of advice if I am missing anything ? 

Best,

**Comment by ahtsan** [comment]
Thank you for trying out this world. Can you share your launch file so that we can better assist you?

**Comment by han-kyung-min** [comment]
Thanks for the reply.
The launch script is as below.

`<launch>`

 ` <arg name="robot" default="fetch"/>`
  
  `<include file="$(find aws_robomaker_small_house_world)/launch/view_small_house.launch"> </include>`

  
  `<include file="$(find fetch_gazebo)/launch/include/$(arg robot).launch.xml" />`
`</launch>`

**Comment by ahtsan** [comment]
did you also run the components in navigation stack? You can take this [launch file](https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/blob/ros1/simulation_ws/src/cloudwatch_simulation/launch/small_house_turtlebot_navigation.launch#L48) for reference.

**Comment by han-kyung-min** [comment]
Thanks for the reply.
Well... Can we start from much more simpler scenario? Let's not consider bring the navigation stack here yet.  I should be able to move the robot in Gazebo with a terminal command: `rostopic pub /cmd_vel geometry_msgs/Twist -r 10 '[0, 0, 0]' '[0, 0, 1]' ` shouldn't I ?

I see that I can rotate the robot if I switch my robot to Turtlebot3.
However, I cannot control a Fetch robot in the same exact environment. Fetch is just stuck there even if I publish /cmd_vel topic.... Why ?

**Comment by ahtsan** [comment]
Did you launch the fetch robot in another world (or even with an empty world) and try publishing to `/cmd_vel`, and it worked?

**Comment by han-kyung-min** [comment]
playground.launch script is provided by Fetch robotics.
The script comes with fetch_gazebo pkg.
/cmd_vel  works there.

`<launch>`

 ` <env name="GAZEBO_MODEL_PATH" value="$(find fetch_gazebo)/models:$(optenv GAZEBO_MODEL_PATH)" />`

  `<arg name="robot" default="fetch"/>`
 ` <arg name="debug" default="false"/>`
`  <arg name="gui" default="true"/>`
 ` <arg name="headless" default="false"/>`

`  <!-- Start Gazebo with a blank world -->`
 ` <include file="$(find gazebo_ros)/launch/empty_world.launch">`
  `  <arg name="debug" value="$(arg debug)" />`
  `  <arg name="gui" value="$(arg gui)" />`
  `  <arg name="paused" value="false"/>`
  `  <arg name="use_sim_time" value="true"/>`
  `  <arg name="headless" value="$(arg headless)"/>`
  `  <arg name="world_name" value="$(find fetch_gazebo)/worlds/test_zone.sdf"/>`
`  </include>`

  `<!-- Oh, you wanted a robot? -->`
  `<include file="$(find fetch_gazebo)/launch/include/$(arg robot).launch.xml" />`

`</launch>`

**Comment by ahtsan** [comment]
I'm able to reproduce it locally. Using the `freight` robot works. I'll look into that and come back to you.

**Comment by ahtsan** [comment]
I verified that robot is moving via rviz. The issue is floor friction -- If you apply the value from [empty_world](https://github.com/arpg/Gazebo/blob/master/models/ground_plane/model.sdf#L16) to the [small_house_world](https://github.com/aws-robotics/aws-robomaker-small-house-world/blob/ros1/models/aws_robomaker_residential_FloorB_01/model.sdf#L25), it will work.

Thanks for bringing this up, that is a good catch. We will think about what's the correct friction value in the world.

If the above works for you, feel free to close this issue.

**Comment by ahtsan** [comment]
Pull requests for
ros1: https://github.com/aws-robotics/aws-robomaker-small-house-world/pull/40
ros2: https://github.com/aws-robotics/aws-robomaker-small-house-world/pull/41

**Comment by han-kyung-min** [comment]
Hello,

Thanks for the prompt reply.
I pulled the new commits. Then, things work OK.

You might want to fix aws-bookstore env. b/c it has the same issue. Or, should I open a new issue there ?

Best regards,

**Comment by ahtsan** [comment]
We have fixes in all the worlds under `aws-robotics`, e.g. for bookstore world, we have https://github.com/aws-robotics/aws-robomaker-bookstore-world/pull/17 and https://github.com/aws-robotics/aws-robomaker-bookstore-world/pull/18

**Comment by han-kyung-min** [comment]
Hello,

This is not an issue. But, not sure where to ask.
Could you please let me know how to cite your gazebo environments ? Could
you send me a link to the bibtex information ?

Best,
